version: "2"
services:
  web:
    build: .
    volumes:
      - ".:/usr/src/app:rw"
      - "/usr/src/app/node_modules/"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
